# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbee392003ecb6043cc530bc598c44b5cc58d4fcb139cd5453d20355164263ffd9e03211a512e8a85831764698d20eac03e32614d4446961edbba2a2c82ddef9

test:
  secret_key_base: 9435646093e49aa44932a0f229b479ebaa917cbf9441f9fa0bdd9d2b27558cdf1bfc186476edc24ae2795301cd12b9c49d0cc6069747d94aefbe8f22ce8098f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
